Web/Areas/Jobs/Controllers/VirtualController.cs
using DataAccess.CommanClass;
using DataAccess.Models;
using DataAccess.ModelsMaster;
using DataAccess.ModelsMasterHelper;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Web.Areas.Jobs.Controllers
{
    public class VirtualController : Controller
    {
        long LoginID = 0;
        string IPAddress = "";
        GetResponse getResponse;
        IOnboardingHelper onboard;

        public VirtualController()
        {
            getResponse = new GetResponse();
            long.TryParse(ClsApplicationSetting.GetSessionValue("LoginID"), out LoginID);
            IPAddress = ClsApplicationSetting.GetIPAddress();
            getResponse.IPAddress = IPAddress;
            getResponse.LoginID = LoginID;
            onboard = new OnboardingModal();
        }

        public ActionResult OnboardBasicDetails(string Key)
        {
            ViewBag.Key = Key;
            getResponse.Param1 = Key;
            getResponse.Doctype = "BasicDetails";
            var result = onboard.GetOnboarding_BasicDetails(getResponse);
            if (result != null)
            {
                if (result.Approved < 0 || result.Approved == 2)
                {
                    return View(result);
                }
                else
                {
                    return View("InfoPage");
                }
            }
            else
            {
                return View("ErrorPage");
            }
        }

        [HttpPost]
        public ActionResult OnboardBasicDetails(string Key, Onboarding.Users.BasicDetails Modal, string Command)
        {
            PostResponse Result = new PostResponse();
            ViewBag.Key = Key;
            Modal.Token = Key;
            Result.SuccessMessage = "Basic Details Can't Update";
            if (ModelState.IsValid)
            {
                Modal.LoginID = LoginID;
                Modal.IPAddress = IPAddress;
                Result = onboard.fnSetOnboarding_BasicDetails(Modal);
            }
            if (Result.Status)
            {
                Result.RedirectURL = "/OnboardBankDetails/" + Key;
            }
            return Json(Result, JsonRequestBehavior.AllowGet);

        }

       
        public ActionResult OnboardBankDetails(string Key)
        {
            ViewBag.Key = Key;
            getResponse.Param1 = Key;
            var result = onboard.GetOnboarding_BankDetails(getResponse);
            if (result != null)
            {
                if (result.Approved < 0 || result.Approved == 2)
                {
                    return View(result);
                }
                else
                {
                    return View("InfoPage");
                }
            }
            else
            {
                return View("ErrorPage");
            }
        }
        [HttpPost]
        public ActionResult OnboardBankDetails(string Key, Onboarding.Users.BankDetails Modal, string Command)
        {
            PostResponse Result = new PostResponse();
            ViewBag.Key = Key;
            Modal.Token = Key;
            Result.SuccessMessage = "Bank Details Can't Update";
            if (ModelState.IsValid)
            {
                Modal.LoginID = LoginID;
                Modal.IPAddress = IPAddress;
                Result = onboard.fnSetOnboarding_BankDetails(Modal);
            }
            if (Result.Status)
            {
                Result.RedirectURL = "/OnboardDocuments/" + Key;
            }
            return Json(Result, JsonRequestBehavior.AllowGet);

        }
        public ActionResult OnboardDocuments(string Key)
        {
            ViewBag.Key = Key;
            getResponse.Param1 = Key;
            getResponse.Doctype = "documents";
            var result = onboard.GetOnboarding_Documents(getResponse);
            if (result != null)
            {
                if (result.Approved < 0 || result.Approved == 2)
                {
                    return View(result);
                }
                else
                {
                    return View("InfoPage");
                }
            }
            else
            {
                return View("ErrorPage");
            }
        }
        [HttpPost]
        public ActionResult OnboardDocuments(string Key, Onboarding.Users.DocumentDetails Modal, string Command)
        {
            PostResponse Result = new PostResponse();
            ViewBag.Key = Key;
            Modal.Token = Key;
            Result.SuccessMessage = "Documents Details Can't Update";
            if (Modal.DocumentsList == null || Modal.DocumentsList.Count == 0)
            {
                Result.SuccessMessage = "Documents List can't be blank";
                return Json(Result, JsonRequestBehavior.AllowGet);
            }
            else if (Modal.DocumentsList.Any(x => x.Attach_ID == null) && Modal.DocumentsList.Any(x => x.Upload == null))
            {
                Result.SuccessMessage = "Please upload file it can't be blank";
                return Json(Result, JsonRequestBehavior.AllowGet);
            }
            if (ModelState.IsValid)
            {
                Modal.LoginID = LoginID;
                Modal.IPAddress = IPAddress;

                if (Modal.DocumentsList != null)
                {
                    UploadAttachment attachModal;
                    foreach (var item in Modal.DocumentsList)
                    {
                        if (item.Upload != null)
                        {
                            attachModal = new UploadAttachment();
                            attachModal.File = item.Upload;
                            attachModal.LoginID = LoginID;
                            attachModal.IPAddress = IPAddress;
                            attachModal.Token = Key;
                            attachModal.Doctype = "onboard";
                            attachModal.Description = item.Description;
                            attachModal.AttachID = item.Attach_ID;

                            var Attach = ClsApplicationSetting.UploadAttachment(attachModal);
                            if (!Attach.Status)
                            {
                                Result.SuccessMessage = Attach.SuccessMessage;
                                return Json(Result, JsonRequestBehavior.AllowGet);
                            }
                        }
                    }

                }
                Result = onboard.fnSetOnboarding_Final(Modal);
            }
            if (Result.Status)
            {
                Result.RedirectURL = "/InfoPage";
            }
            return Json(Result, JsonRequestBehavior.AllowGet);

        }
        public ActionResult ErrorPage()
        {
            return View();
        }
        public ActionResult InfoPage()
        {
            return View();
        }


    }
}

Web/Areas/Jobs/Views/Virtual/ErrorPage.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>market-wp.com</title>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/5.0.0/normalize.min.css">
    <link rel="stylesheet" href="~/Areas/Jobs/assets/css/errorpage.css" />
</head>

<body>

   <div id='oopss'>
                <div id='error-text'  class="row p-4">
                    <div class="col-xl-6 col-md-6 col-sm-12 text-center d-flex justify-content-center align-items-center flex-wrap">
                        <img src="~/Areas/Jobs/assets/Images/41741-removebg-preview.png"  class="img-fluid" alt="404">
                    </div>

                    <div class="col-xl-6 col-md-6 col-sm-12 flex-wrap d-flex flex-column align-items-xl-start justify-content-center">
                        <div>
                            <h1>404</h1>
                            <h5>
                                Page not found!
                            </h5>
                 
                                <p>  We're sorry, the page you're requested could not be found. Please go back to the home page!</p>
                            <a href="" type="button" class="mb-4 button">Go Home</a>
                     



                        </div>

                  </div>
            </div>
        </div>
    @*<div id='oopss1'>
        <div id='error-text' class="row ">
            <div class="col-xl-6  col-sm-12 text-center d-flex justify-content-center align-items-center">
                <img src="~/Areas/Jobs/assets/Images/2(1).png" alt="404"/>
            </div>

            <div class="col-xl-6 col-sm-12  d-flex flex-column align-items-xl-start justify-content-center">
                <div>
                    <h1>404</h1>
                    <p class="">
                        Page not found
                    </p>
                    <div class="sorry-text">
                        <p>  We're sorry, the page your requested could not be found.<br /> Please go back to the home page!</p>
                        <button class="mb-4"><a href="">Go Home</a></button>
                    </div>



                </div>

            </div>
        </div>
    </div>*@


</body>

</html>

Web/Areas/Jobs/Views/Virtual/InfoPage.cshtml
@{
    ViewBag.Title = "InfoPage";
    Layout = "~/Areas/Jobs/Views/Shared/_Layout.cshtml";
}

<div class="d-flex text-center justify-content-center align-items-center" id="info" >
    <div>
        <img src="~/Areas/Jobs/assets/Images/mark-removebg-preview.png" />
        <h1>Your Submission has been successful!</h1>
        <p>Thanks we have recieve your submission.</p>
        <button class="mb-4"><a href="">Go Home</a></button>
    </div>

</div>

Web/Areas/Jobs/Views/Virtual/OnboardBankDetails.cshtml
@model Onboarding.Users.BankDetails

<div class="row" id="demoform2">
    <div class="col-sm-12 col-xl-12 col1 text-center brand-logo">
        <div class="container">
            <h1 class="pt-3">Requirter Details</h1>
        </div>
    </div>
    <div class="col-xl-12 col-sm-12">

        @using (Ajax.BeginForm("OnboardBankDetails", "Virtual",
          new { Key = ViewBag.Key },
           new AjaxOptions { HttpMethod = "POST", OnSuccess = "OnSuccess" },
              new { @id = "OnboardBankDetailsForm" })
      )
        {
            @Html.ValidationSummary(false);
            <!-- One "tab" for each step in the form: -->
            <div class="tab" id="regForm">
                <div class="basic">
                    <div class="icons">
                        <span class="user-icon">
                            <img src="~/Areas/Jobs/assets/Images/piggy-bank.png" />

                        </span>
                        <h4 class="mt-4">Bank Details</h4>
                    </div>
                    <p class="">Please Fill All Your Details</p>

                    <div class="field1 my-2 row">
                        <div class="col-xl-3  col-md-3 col-sm-12">
                            <div class="form-floating form-group">
                                <label for="BankName">Bank Name <sup>*</sup></label>
                                @Html.TextBoxFor(model => model.BankName, new { @class = "form-control", @id = "floatingInput", })
                                @Html.ValidationMessageFor(model => model.BankName, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="col-xl-3  col-md-3 col-sm-12">
                            <div class="form-floating form-group">
                                <label for="AccountNo">Account No <sup>*</sup></label>
                                @Html.TextBoxFor(model => model.AccountNo, new { @class = "form-control", @id = "floatingInput" })
                                @Html.ValidationMessageFor(model => model.AccountNo, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="col-xl-3  col-md-3 col-sm-12">
                            <div class="form-floating form-group">
                                <label for="AccountNo"> Branch <sup>*</sup></label>
                                @Html.TextBoxFor(model => model.BankBranch, new { @class = "form-control", @id = "floatingInput" })
                                @Html.ValidationMessageFor(model => model.BankBranch, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="col-xl-3  col-md-3 col-sm-12">

                            <div class="form-floating form-group">
                                <label for="IFSCCode">IFSC Code <sup>*</sup></label>
                                @Html.TextBoxFor(model => model.IFSCCode, new { @class = "form-control", })
                                @Html.ValidationMessageFor(model => model.IFSCCode, "", new { @class = "text-danger" })
                            </div>
                        </div>

                    </div>
                    <div class=" row my-2">
                        <div class="col-xl-3  col-md-3 col-sm-12">
                            <div class="form-floating form-group">
                                <label for="IFSCCode">Nominee Name</label>
                                @Html.TextBoxFor(model => model.NomineeName, new { @class = "form-control", })
                                @Html.ValidationMessageFor(model => model.NomineeName, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="col-xl-3  col-md-3 col-sm-12">
                            <div class="form-floating form-group">
                                <label for="NomineeRelation">Relationship with Nominee</label>
                                @Html.TextBoxFor(model => model.NomineeRelation, new { @class = "form-control", })
                                @Html.ValidationMessageFor(model => model.NomineeRelation, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="col-xl-3  col-md-3 col-sm-12">
                            <div class="form-floating form-group">
                                <label for="NomineeDOB">Nominee DOB</label>
                                @Html.TextBoxFor(model => model.NomineeDOB, new { @class = "form-control", @type = "date" })
                                @Html.ValidationMessageFor(model => model.NomineeDOB, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>
                    


                </div>
            </div>
            <div style="overflow:auto;">
                <div class="d-flex justify-content-center ">
                    <a href="/OnboardBasicDetails/@ViewBag.Key" type="button" id="prevBtn" class="button">Previous</a>
                    <button type="submit" class="button" name="Command" value="Add" id="nextBtn"><i class="fa fa-paper-plane" aria-hidden="true"></i> Next</button>
                </div>
            </div>
        }
    </div>

</div>
@section scripts    {

    @System.Web.Optimization.Scripts.Render("~/bundle/unobtrusivejs")

    <script>
        function OnSuccess(obj) {
            if (obj.Status) {
                SuccessToaster(obj.SuccessMessage);
                window.location.href = obj.RedirectURL;
            }
            else {
                CloseLoadingDialog();
                FailToaster(obj.SuccessMessage);

            }
        }


    </script>
}

Web/Areas/Jobs/Views/Virtual/OnboardDocuments.cshtml
@model Onboarding.Users.DocumentDetails

<div class="row" id="demoform2">
    <div class="col-sm-12 col-xl-12 col1 text-center brand-logo">
        <div class="container">
            <h1 class="pt-3">Requirter Details</h1>
        </div>
    </div>
    <div class="col-xl-12 ">

        @using (Ajax.BeginForm("OnboardDocuments", "Virtual",
          new { Key = ViewBag.Key },
           new AjaxOptions { HttpMethod = "POST", OnSuccess = "OnSuccess" },
              new { @id = "OnboardDocumentsForm", @enctype = "multipart/form-data" })
      )
        {
            @Html.ValidationSummary(false);

            <div class="tab" id="regForm">
                <div class="basic">
                    <div class="text-center icons">
                        <span class="user-icon">
                            <img src="~/Areas/Jobs/assets/Images/cloud-computing.png" />
                    </div>
                    <div class="mt-4  head"><h4>Upload Documents</h4></div>
                    <div class="row " id="form-upload">

                        <div class="col-lg-12 " id="documents">
                            <div class="card mt-4 ">
                                <div class="my-4"> <a id="btn-add" onclick="AddNewRow()"><span><img src="~/Areas/Jobs/assets/Images/icons8-plus-30.png" /></span> Add New Row</a></div>


                                <div class="table-responsive">
                                    <table id="tbldoc" class="table" cellpadding="0" cellspacing="0">
                                        <thead>
                                            <tr>
                                                <th>Description</th>
                                                <th>File</th>
                                                <th>Upload</th>
                                                <th>Action</th>
                                            </tr>
                                        </thead>

                                        <tbody>
                                            @if (Model.DocumentsList != null)
                                            {
                                                for (int i = 0; i < Model.DocumentsList.Count; i++)
                                                {
                                                    <tr>
                                                        <td>
                                                            
                                                            @Html.HiddenFor(model => Model.DocumentsList[i].Attach_ID,new {@class= "Attach_ID" })

                                                            @if (!string.IsNullOrEmpty(Model.DocumentsList[i].Description))
                                                            {
                                                                @Html.TextAreaFor(model => Model.DocumentsList[i].Description, new { @class = "form-control", @readonly = "readonly" })
                                                                @Html.ValidationMessageFor(model => Model.DocumentsList[i].Description, "", new { @class = "text-danger" })
                                                            }
                                                            else
                                                            {
                                                                @Html.TextAreaFor(model => Model.DocumentsList[i].Description, new { @class = "form-control" })
                                                                @Html.ValidationMessageFor(model => Model.DocumentsList[i].Description, "", new { @class = "text-danger" })
                                                            }
                                                        </td>
                                                        <td>
                                                            @if (!string.IsNullOrEmpty(Model.DocumentsList[i].AttachmentPath))
                                                            {
                                                                <a title="click to download the document" target="_blank" href="@Model.DocumentsList[i].AttachmentPath">Doc</a>
                                                            }
                                                           

                                                        </td>
                                                        <td>
                                                            @Html.TextBoxFor(model => Model.DocumentsList[i].Upload, new { @class = "form-control", @type = "file" })
                                                            @Html.ValidationMessageFor(model => Model.DocumentsList[i].Upload, "", new { @class = "text-danger" })
                                                        </td>
                                                      
                                                        <td>
                                                           
                                                                <a onclick="DeleteRow(this)" class="remove "><i class="fas fa-window-close red-clr" aria-hidden="true"></i></a>
                                                            
                                                           
                                                        </td>
                                                    </tr>
                                                }
                                            }


                                        </tbody>
                                    </table>

                                </div>



                            </div>
                        </div>

                    </div>


                </div>
            </div>

            <div style="overflow:auto;">
                <div class="d-flex justify-content-center ">

                    <a href="/OnboardBankDetails/@ViewBag.Key" type="button" id="prevBtn" class="button">Previous</a>
                    <button type="submit" class="button" name="Command" value="Add" id="nextBtn"><i class="fa fa-paper-plane" aria-hidden="true"></i> Submit</button>

                </div>
            </div>
        }
    </div>

</div>
@section scripts    {

    @System.Web.Optimization.Scripts.Render("~/bundle/unobtrusivejs")

    <script>
        function OnSuccess(obj) {
            console.log(obj)
            if (obj.Status) {
                SuccessToaster(obj.SuccessMessage);
                window.location.href = obj.RedirectURL;
            }
            else {
                CloseLoadingDialog();
                FailToaster(obj.SuccessMessage);

            }
        }

        // add new Row
        function AddNewRow() {
            var LastTRCount = parseInt($('#tbldoc').find("tbody tr").length) - 1;
            var $tableBody = $('#tbldoc').find("tbody"),
                $trLast = $tableBody.find("tr:last"),
                $trNew = $trLast.clone();
            $trNew.find("td:last").html('<a onclick="DeleteRow(this)" class="remove" data-toggle="tooltip" data-original-title="Remove"><i class="fas fa-window-close red-clr" aria-hidden="true"></i></a>');

            $trNew.find("input").each(function (i) {
                $(this).attr({
                    'id': function (_, name) { return name.replace('_' + LastTRCount + '_', '_' + (parseInt(LastTRCount) + 1) + '_'); },
                    'name': function (_, name) { return name.replace('[' + LastTRCount + ']', '[' + (parseInt(LastTRCount) + 1) + ']'); },
                });

                $(this).val("");


            });
            $trNew.find("textarea").each(function (i) {
                $(this).attr({
                    'id': function (_, name) { return name.replace('_' + LastTRCount + '_', '_' + (parseInt(LastTRCount) + 1) + '_'); },
                    'name': function (_, name) { return name.replace('[' + LastTRCount + ']', '[' + (parseInt(LastTRCount) + 1) + ']'); },
                });
                $(this).val('');
                $(this).removeAttr("readonly")
            });

            $trNew.find("span").each(function (i) {
                if ($(this).attr("data-valmsg-for")) {
                    $(this).attr({
                        'data-valmsg-for': function (_, name) { return name.replace('[' + LastTRCount + ']', '[' + (parseInt(LastTRCount) + 1) + ']'); }
                    });
                }
                if ($(this).attr("for")) {
                    $(this).attr({
                        'for': function (_, name) { return name.replace('_' + LastTRCount + '_', '_' + (parseInt(LastTRCount) + 1) + '_'); }
                    });
                }
            });

            $trLast.after($trNew);
            var form = $("#OnboardDocumentsForm").closest("form");
            form.removeData('validator');
            form.removeData('unobtrusiveValidation');
            $.validator.unobtrusive.parse(form);
        }

        function DeleteRow(obj) {
            var ID = Number($(obj).closest("tr").find("input:hidden[class=Attach_ID]").val());
            alert(ID)
            var Msg = 'Are you sure want to delete  ?';
            ConfirmMsgBox(Msg, '', function () {
                if (ID !=0) {
                    var myobj = DelRecordJson(ID, 'OnboardingAttachment');
                    console.log(myobj)
                    if (!myobj.Status) {
                        FailToaster(myobj.SuccessMessage);

                    } else {
                        SuccessToaster(myobj.SuccessMessage);
                        window.location.reload(true);

                    }
                } else {
                    $(obj).closest('tr').remove();
                }
            });

        }
        
    </script>
}