Web/Controllers/HelpDeskController.cs
using DataAccess.CommanClass;
using DataAccess.Models;
using DataAccess.ModelsMaster;
using DataAccess.ModelsMasterHelper;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Web.CommonClass;

namespace Web.Controllers
{
    [CheckLoginFilter]
    public class HelpDeskController : Controller
    {
        long LoginID = 0;
        string IPAddress = "";
        GetResponse getResponse;
        IHelpDeskHelper help;

        public HelpDeskController()
        {

            getResponse = new GetResponse();
            long.TryParse(ClsApplicationSetting.GetSessionValue("LoginID"), out LoginID);
            IPAddress = ClsApplicationSetting.GetIPAddress();
            getResponse.IPAddress = IPAddress;
            getResponse.LoginID = LoginID;
            help = new HelpDeskModal();

        }
        public string RenderRazorViewToString(string viewName, object model)
        {
            ViewData.Model = model;
            using (var sw = new StringWriter())
            {
                var viewResult = ViewEngines.Engines.FindPartialView(ControllerContext,
                                                                         viewName);
                var viewContext = new ViewContext(ControllerContext, viewResult.View,
                                             ViewData, TempData, sw);
                viewResult.View.Render(viewContext, sw);
                viewResult.ViewEngine.ReleaseView(ControllerContext, viewResult.View);
                return sw.GetStringBuilder().ToString();
            }
        }
        public ActionResult CategoryList(string src)
        {
            ViewBag.src = src;
            string[] GetQueryString = ClsApplicationSetting.DecryptQueryString(src);
            ViewBag.GetQueryString = GetQueryString;
            ViewBag.MenuID = GetQueryString[0];
            List<Helpdesk.Category.List> result = new List<Helpdesk.Category.List>();
            result = help.GetHelpdesk_CategoryList(getResponse);
            return View(result);
        }
        public ActionResult _CategoryAdd(string src)
        {
            ViewBag.src = src;
            string[] GetQueryString = ClsApplicationSetting.DecryptQueryString(src);
            ViewBag.GetQueryString = GetQueryString;
            ViewBag.MenuID = GetQueryString[0];
            ViewBag.CategoryID = GetQueryString[2];
            long CategoryID = 0;
            long.TryParse(ViewBag.CategoryID, out CategoryID);
            getResponse.ID = CategoryID;
            Helpdesk.Category.Add result = new Helpdesk.Category.Add();
            if (CategoryID > 0)
            {
                result = help.GetHelpdesk_Category(getResponse);
            }
            return PartialView(result);
        }

        [HttpPost]
        public ActionResult _CategoryAdd(string src, Helpdesk.Category.Add Modal, string Command)
        {
            PostResponse Result = new PostResponse();
            ViewBag.src = src;
            string[] GetQueryString = ClsApplicationSetting.DecryptQueryString(src);
            ViewBag.GetQueryString = GetQueryString;
            ViewBag.MenuID = GetQueryString[0];
            ViewBag.CategoryID = GetQueryString[2];
            long CategoryID = 0;
            long.TryParse(ViewBag.CategoryID, out CategoryID);
            Result.SuccessMessage = "Category Can't Update";
            if (ModelState.IsValid)
            {
                Modal.LoginID = LoginID;
                Modal.IPAddress = IPAddress;
                Modal.CategoryID = CategoryID;
                Result = help.fnSetHelpdesk_Category(Modal);

            }
            if (Result.Status)
            {
                Result.RedirectURL = "/HelpDesk/CategoryList?src=" + ClsCommon.Encrypt(ViewBag.MenuID.ToString() + "*/HelpDesk/CategoryList");
            }
            return Json(Result, JsonRequestBehavior.AllowGet);

        }

        public ActionResult SubCategoryList(string src)
        {
            ViewBag.src = src;
            string[] GetQueryString = ClsApplicationSetting.DecryptQueryString(src);
            ViewBag.GetQueryString = GetQueryString;
            ViewBag.MenuID = GetQueryString[0];
            List<Helpdesk.SubCategory.List> result = new List<Helpdesk.SubCategory.List>();
            result = help.GetHelpdesk_SubCategoryList(getResponse);
            return View(result);
        }
        public ActionResult _SubCategoryAdd(string src)
        {
            ViewBag.src = src;
            string[] GetQueryString = ClsApplicationSetting.DecryptQueryString(src);
            ViewBag.GetQueryString = GetQueryString;
            ViewBag.MenuID = GetQueryString[0];
            ViewBag.SubCategoryID = GetQueryString[2];
            long SubCategoryID = 0;
            long.TryParse(ViewBag.SubCategoryID, out SubCategoryID);
            getResponse.ID = SubCategoryID;
            Helpdesk.SubCategory.Add result = new Helpdesk.SubCategory.Add();
            result = help.GetHelpdesk_SubCategory(getResponse);

            return PartialView(result);
        }

        [HttpPost]
        public ActionResult _SubCategoryAdd(string src, Helpdesk.SubCategory.Add Modal, string Command)
        {
            PostResponse Result = new PostResponse();
            ViewBag.src = src;
            string[] GetQueryString = ClsApplicationSetting.DecryptQueryString(src);
            ViewBag.GetQueryString = GetQueryString;
            ViewBag.MenuID = GetQueryString[0];
            ViewBag.SubCategoryID = GetQueryString[2];
            long SubCategoryID = 0;
            long.TryParse(ViewBag.SubCategoryID, out SubCategoryID);
            Result.SuccessMessage = "Sub Category Can't Update";
            if (ModelState.IsValid)
            {
                Modal.LoginID = LoginID;
                Modal.IPAddress = IPAddress;
                Modal.SubCategoryID = SubCategoryID;
                Result = help.fnSetHelpdesk_SubCategory(Modal);

            }
            if (Result.Status)
            {
                Result.RedirectURL = "/HelpDesk/SubCategoryList?src=" + ClsCommon.Encrypt(ViewBag.MenuID.ToString() + "*/HelpDesk/SubCategoryList");
            }
            return Json(Result, JsonRequestBehavior.AllowGet);

        }



        public ActionResult StatusList(string src)
        {
            ViewBag.src = src;
            string[] GetQueryString = ClsApplicationSetting.DecryptQueryString(src);
            ViewBag.GetQueryString = GetQueryString;
            ViewBag.MenuID = GetQueryString[0];
            List<Helpdesk.Status.List> result = new List<Helpdesk.Status.List>();
            result = help.GetHelpdesk_StatusList(getResponse);
            return View(result);
        }
        public ActionResult _StatusAdd(string src)
        {
            ViewBag.src = src;
            string[] GetQueryString = ClsApplicationSetting.DecryptQueryString(src);
            ViewBag.GetQueryString = GetQueryString;
            ViewBag.MenuID = GetQueryString[0];
            ViewBag.StatusID = GetQueryString[2];
            long StatusID = 0;
            long.TryParse(ViewBag.StatusID, out StatusID);
            getResponse.ID = StatusID;
            Helpdesk.Status.Add result = new Helpdesk.Status.Add();
            if (StatusID > 0)
            {
                result = help.GetHelpdesk_Status(getResponse);
            }

            return PartialView(result);
        }

        [HttpPost]
        public ActionResult _StatusAdd(string src, Helpdesk.Status.Add Modal, string Command)
        {
            PostResponse Result = new PostResponse();
            ViewBag.src = src;
            string[] GetQueryString = ClsApplicationSetting.DecryptQueryString(src);
            ViewBag.GetQueryString = GetQueryString;
            ViewBag.MenuID = GetQueryString[0];
            ViewBag.StatusID = GetQueryString[2];
            long StatusID = 0;
            long.TryParse(ViewBag.StatusID, out StatusID);
            Result.SuccessMessage = "Status Can't Update";
            if (ModelState.IsValid)
            {
                Modal.LoginID = LoginID;
                Modal.IPAddress = IPAddress;
                Modal.StatusID = StatusID;
                Result = help.fnSetHelpdesk_Status(Modal);

            }
            if (Result.Status)
            {
                Result.RedirectURL = "/HelpDesk/StatusList?src=" + ClsCommon.Encrypt(ViewBag.MenuID.ToString() + "*/HelpDesk/StatusList");
            }
            return Json(Result, JsonRequestBehavior.AllowGet);

        }

        public ActionResult MyTicketsList(string src)
        {
            ViewBag.src = src;
            string[] GetQueryString = ClsApplicationSetting.DecryptQueryString(src);
            ViewBag.GetQueryString = GetQueryString;
            ViewBag.MenuID = GetQueryString[0];
            MyTab.Approval Modal = new MyTab.Approval();
            Modal.Approved = 1;
            return View(Modal);
        }
        public ActionResult _MyTicketsList(string src, MyTab.Approval Modal)
        {
            ViewBag.src = src;
            string[] GetQueryString = ClsApplicationSetting.DecryptQueryString(src);
            ViewBag.GetQueryString = GetQueryString;
            ViewBag.MenuID = GetQueryString[0];
            Modal.LoginID = LoginID;
            Modal.IPAddress = IPAddress;
            List<Helpdesk.Ticket.List> Result = new List<Helpdesk.Ticket.List>();
            Result = help.GetHelpdesk_Tickets_List(Modal);
            return PartialView(Result);

        }

        //public ActionResult HelpdeskImageUpload(IEnumerable<HttpPostedFileBase> files)
        //{
        //    List<PostResponse> listFiles = new List<PostResponse>();
        //    PostResponse _path;

        //    string PhysicalPath = ClsApplicationSetting.GetPhysicalPath("HelpdeskTemp");
        //    foreach (var file in files)
        //    {
        //        if (file.ContentLength > 0)
        //        {

Web/Views/HelpDesk/CreateTicket.cshtml
@model Helpdesk.Ticket.Add
@{
    var TicketPriority = new List<SelectListItem>()
{
             new SelectListItem() {Text="Low", Value="Low"},
             new SelectListItem() {Text="Medium", Value="Medium"},
             new SelectListItem() {Text="High", Value="High"},
        };
}
@section style{

    @Html.IncludeVersionedCss(Url.Content("/assets/design/plugins/fileupload/css/fileupload.css"))

}
<div class="page-header">
    <div class="page-leftheader">
        <h4 class="page-title">Create Ticket </h4>
    </div>

</div>
<div class="card">
    <div class="card-body">

        @using (Ajax.BeginForm("CreateTicket", "HelpDesk",
                new { src = ViewBag.src },
                 new AjaxOptions { HttpMethod = "POST", OnSuccess = "OnSuccess", OnBegin = "ShowLoadingDialog()" },
                    new { @id = "CreateTicketForm", @enctype = "multipart/form-data" })
            )
        {
            @Html.HiddenFor(x => Model.TicketID)
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 form-group">
                    <label>Subject <sup>*</sup></label>
                    @Html.TextAreaFor(model => model.Subject, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Subject, "", new { @class = "text-danger" })
                </div>

                <div class="col-lg-3 col-md-3 col-sm-3 form-group">
                    <label>Priority<sup>*</sup></label>
                    @Html.DropDownListFor(n => n.TicketPriority, TicketPriority, "Select Priority",
                        new { @class = "form-control applyselect" })
                    @Html.ValidationMessageFor(model => model.TicketPriority, "", new { @class = "text-danger" })
                </div>
                <div class="col-lg-3 col-md-3 col-sm-3 form-group">
                    <label>Category<sup>*</sup></label>
                    @Html.DropDownListFor(n => n.CategoryID, new SelectList(Model.CategoryList, "ID", "Name", Model.CategoryID), "Select Category",
                        new { @class = "form-control applyselect", @Onchange = "FillSubCategory()" })
                    @Html.ValidationMessageFor(model => model.CategoryID, "", new { @class = "text-danger" })
                </div>
                <div class="col-lg-6 col-md-6 col-sm-6 form-group">
                    <label>Sub Category<sup>*</sup></label>
                    @Html.DropDownListFor(n => n.SubCategoryID, new SelectList(Model.SubCategoryList, "ID", "Name", Model.SubCategoryID), "Select Sub Category",
                        new { @class = "form-control applyselect" })
                    @Html.ValidationMessageFor(model => model.SubCategoryID, "", new { @class = "text-danger" })
                </div>
                <div class="col-lg-12 col-md-12 col-sm-12 form-group">
                    <label>Optinal Users</label>
                    @Html.DropDownListFor(n => n.OptionalUsers, new SelectList(Model.UserList, "ID", "Name", Model.OptionalUsers),
                        new { @class = "form-control applyselect", @multiple = "multiple" })
                    @Html.ValidationMessageFor(model => model.OptionalUsers, "", new { @class = "text-danger" })
                </div>

                <div class="col-lg-12 col-md-12 col-sm-12 form-group">
                    <label>Message <sup>*</sup></label>
                    @Html.TextAreaFor(model => model.Message, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Message, "", new { @class = "text-danger" })
                </div>

                <div class="col-lg-12 col-md-12 col-sm-12 form-group">
                    <label>Attachments</label>
                    @Html.TextBoxFor(x => x.Upload, new { @class = "dropify", @type = "file", @multiple= "multiple" })
                    @Html.ValidationMessageFor(model => model.Upload, "", new { @class = "text-danger" })
                </div>

                <div class="col-lg-12 form-group">

                    <button type="submit" class="btn btn-indigo" name="Command" value="Add"><i class="fa fa-paper-plane" aria-hidden="true"></i> Submit</button>
                    <a href="@Url.Action("MyTicketsList",new { src = ClsCommon.Encrypt(ViewBag.MenuID+"*"+"/HelpDesk/MyTicketsList") })" type="button" class="btn btn-sm  close-btn">Back To List</a>

                </div>

            </div>
        }

    </div>
</div>
@section scripts    {

    @System.Web.Optimization.Scripts.Render("~/bundle/unobtrusivejs")

    @Html.IncludeVersionedJs(Url.Content("~/ckeditor/ckeditor.js"))
    @Html.IncludeVersionedJs(Url.Content("/assets/design/plugins/fileupload/js/dropify.js"))
    @Html.IncludeVersionedJs(Url.Content("/assets/design/js/filupload.js"))
    <script>
        CKEDITOR.replace("Message");

        function OnSuccess(obj) {
            if (obj.Status) {
                SuccessToaster(obj.SuccessMessage);
                window.location.href = obj.RedirectURL;
            }
            else {
                CloseLoadingDialog();
                FailToaster(obj.SuccessMessage);

            }
        }

        function FillSubCategory() {
            var ID = $("#CategoryID").find("option:selected").val();
            if (ID != '') {
                var data = GetDropDownList(ID, "Helpdesk_SubCategoryList");
                if (data != '') {
                    $("#SubCategoryID").empty();
                    $("#SubCategoryID").append($("<option />").val("").text("Select"));
                    $(data).each(function () {
                        $("#SubCategoryID").append($("<option />").val(this.ID).text(this.Name));
                        $("#SubCategoryID").select2();

                    });
                    CloseLoadingDialog();
                } else {
                    $("#SubCategoryID").empty();
                    $("#SubCategoryID").append($("<option />").val("").text("Select"));
                }
            } else {
                $("#SubCategoryID").empty();
                $("#SubCategoryID").append($("<option />").val("").text("Select"));
            }
        }
    </script>
}

Web/Views/HelpDesk/MyTicketsList.cshtml
@model MyTab.Approval
@section style{
    @System.Web.Optimization.Styles.Render("~/bundle/dataTablecss")
}

@Html.Partial("ListHeader_Partial", "My Tickets")

<div class="row">
    <div class="col-lg-12 ">
        <div class="card">
            <div class="card-body">
                <div class="">

                    <input type="hidden" id="hdnAddUrl" name="hdnAddUrl" value="@Url.Action("CreateTicket",new { src = ClsCommon.Encrypt(ViewBag.MenuID+"*"+"/HelpDesk/CreateTicket"+"*"+"0") })" />

                    @using (Ajax.BeginForm("_MyTicketsList", "HelpDesk",
                             new { src = ClsCommon.Encrypt(ViewBag.MenuID + "*" + "/HelpDesk/_MyTicketsList") },
                              new AjaxOptions { HttpMethod = "POST", OnSuccess = "OnSuccess", OnBegin = "ShowLoadingDialog()" },
                                 new { @id = "_MyTicketsListsForm" })
                         )
                    {
                        <div class="row">
                            <div class="tabmargin">
                                @Html.HiddenFor(x => x.Approved)
                                <ul id="tabs" class="nav nav-tabs " role="tablist">
                                    <li class="nav-item"> <a tabvalue="1" class="nav-link ripplelink AnchorApproval @(Model.Approved == 1 ? "active" : "")" data-toggle="tab" role="tab">Pending</a> </li>
                                    <li class="nav-item"> <a tabvalue="2" class="nav-link ripplelink AnchorApproval @(Model.Approved == 2 ? "active" : "") " data-toggle="tab" role="tab">In Process</a></li>
                                    <li class="nav-item"> <a tabvalue="3" class="nav-link ripplelink AnchorApproval @(Model.Approved == 3 ? "active" : "") " data-toggle="tab" role="tab">Forward</a></li>
                                    <li class="nav-item"> <a tabvalue="4" class="nav-link ripplelink AnchorApproval @(Model.Approved == 4 ? "active" : "") " data-toggle="tab" role="tab">Completed</a></li>
                                </ul>

                            </div>
                            <div class="col-sm-2 form-group" style="display:none">
                                <label class="small">&nbsp;</label>
                                <button type="submit" id="btnSearch" name="Command" value="Add" class="btn btndefault pull-right form-control">
                                    <i class="fa fa-search"></i>  Search
                                </button>
                            </div>
                        </div>
                    }

                    <div class="row">
                        <div class="col-md-12">
                            <div id="TargetDiv">

                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>

</div>





@section scripts    {
    @System.Web.Optimization.Scripts.Render("~/bundle/dataTablesjs")

    @System.Web.Optimization.Scripts.Render("~/bundle/unobtrusivejs")

    <script>
        function OnBegin() {
            $("#TargetDiv").empty();
            $("#TargetDiv").html('<img src="/assets/design/images/loader.gif" class="imgloader" />');
        }
        $(document).ready(function () {
            $("#btnSearch").click();
        });


        $('.AnchorApproval').on('click', function (e) {
            e.preventDefault();
            e.stopPropagation();
            var att = $(this).attr("tabvalue");
            $(".AnchorApproval.active").removeClass("active");
            $(this).addClass("active");
            $("#Approved").val(att);
            $('#btnSearch').click();
        });

        function OnSuccess(obj) {
            $("#TargetDiv").empty();
            $("#TargetDiv").html(obj);
            CloseLoadingDialog();
            DatatableScripts();
        }
       

    </script>

}

Web/Views/HelpDesk/_CategoryAdd.cshtml
@model Helpdesk.Category.Add

@using (Ajax.BeginForm("_CategoryAdd", "HelpDesk",
        new { src = ViewBag.src },
         new AjaxOptions { HttpMethod = "POST", OnSuccess = "OnSuccess", OnBegin = "ShowLoadingDialog()" },
            new { @id = "_CategoryAddForm" })
    )
{


    
    @Html.HiddenFor(x => Model.CategoryID)
<div class="row">
    <div class="col-lg-12 col-md-12 col-sm-12 form-group">
        <label> Name<sup>*</sup></label>
        @Html.TextBoxFor(model => model.CategoryName, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.CategoryName, "", new { @class = "text-danger" })
    </div>
    <div class="col-lg-12 col-md-12 col-sm-12 form-group">
        <label>Description </label>
        @Html.TextAreaFor(model => model.CategoryDesc, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.CategoryDesc, "", new { @class = "text-danger" })
    </div>


    <div class="col-lg-6 col-md-6 col-sm-6 form-group">
        <label>Priority</label>
        @Html.TextBoxFor(model => model.Priority, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.Priority, "", new { @class = "text-danger" })
    </div>

    <div class="col-lg-12 form-group">

        @if (Model.CategoryID > 0)
        {
            <button type="submit" class="btn btn-indigo" name="Command" value="Add"><i class="fa fa-paper-plane" aria-hidden="true"></i> Update</button>
        }
        else
        {
            <button type="submit" class="btn btn-indigo" name="Command" value="Add"><i class="fa fa-paper-plane" aria-hidden="true"></i> Submit</button>
        }
    </div>

</div>
}

Web/Views/HelpDesk/_MyTicketsList.cshtml
@model IList<Helpdesk.Ticket.List>

<div class="table-responsive">
    <table id="example" class="table table-bordered text-nowrap key-buttons">
        <thead>
            <tr>
                <th>S.no.</th>
                <th>Ticket No</th>
                <th>Category</th>
                <th>Sub Category</th>
                <th>Subject</th>
                <th>Status</th>
                <th>Priority</th>


                <th>Notes</th>
                <th>Next Date</th>
                <th>Updated Date</th>
                <th>Updated by</th>
                <th>IP Address</th>
            </tr>

        </thead>
        <tbody>
            @{ int count = 0;}
            @foreach (Helpdesk.Ticket.List item in Model)
            {
                count++;
            <tr>
                <td>
                    @count
                    <input type="hidden" name="I" value="@item.TicketID" />
                    <input type="hidden" name="N" value="@item.TicketNo" />
                </td>

                <td>
                    <a title="click to view details" class="green-clr" href="@Url.Action("TicketDetails","HelpDesk", new { src = ClsCommon.Encrypt(ViewBag.MenuID + "*" + "/HelpDesk/TicketDetails*" + item.TicketID) })" data-toggle='tooltip'> @item.TicketNo</a>
                </td>
                <td>@item.CategoryName</td>
                <td>@item.SubCategoryName</td>
                <td>@item.Subject</td>
                <td style="color:@item.CurrentStatus_Color"><b> @item.CurrentStatus</b> </td>
                <td>@item.TicketPriority </td>


                <td>@Html.Raw(item.Latest_Notes)</td>
                <td>@item.Latest_NextDate</td>
                <td>@item.ModifiedDate</td>
                <td>@item.ModifiedBy</td>
                <td>@item.IPAddress</td>
            </tr>
            }

        </tbody>
    </table>
</div>

Web/Views/HelpDesk/_NotesAdd.cshtml
@model Helpdesk.Notes.Add
<div class="card">
    <div class="card-body">

        @using (Ajax.BeginForm("_NotesAdd", "HelpDesk",
                new { src = ViewBag.src },
                 new AjaxOptions { HttpMethod = "POST", OnSuccess = "OnNotesSuccess", OnBegin = "ShowLoadingDialog()" },
                    new { @id = "_NotesAddForm", @enctype = "multipart/form-data" })
            )
        {
            @Html.HiddenFor(x => Model.TicketID)
        <div class="row">
            <div class="col-lg-6 col-md-6 col-sm-6 form-group">
                <label>Status<sup>*</sup></label>
                @Html.DropDownListFor(n => n.StatusID, new SelectList(Model.StatusList, "ID", "Name", Model.StatusID), "Select Status",
                    new { @class = "form-control applyselect", @Onchange = "ShowUser()" })
                @Html.ValidationMessageFor(model => model.StatusID, "", new { @class = "text-danger" })
            </div>
            <div class="col-lg-6 col-md-6 col-sm-6 form-group" style="display:none" id="userdiv">
                <label>Users<sup>*</sup></label>
                @Html.DropDownListFor(n => n.UserID, new SelectList(Model.UserList, "ID", "Name", Model.UserID), "Select User",
                    new { @class = "form-control applyselect" })
                @Html.ValidationMessageFor(model => model.UserID, "", new { @class = "text-danger" })
            </div>
            <div class="col-lg-6 col-md-6 col-sm-6 form-group">
                <label>Next Date <sup>*</sup></label>
                @Html.TextBoxFor(model => model.NextDate, new { @class = "form-control", @Type = "datetime-local" })
                @Html.ValidationMessageFor(model => model.NextDate, "", new { @class = "text-danger" })
            </div>

            <div class="col-lg-12 col-md-12 col-sm-12 form-group">
                <label>Notes <sup>*</sup></label>
                @Html.TextAreaFor(model => model.Notes, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Notes, "", new { @class = "text-danger" })
            </div>
            <div class="col-lg-12 col-md-12 col-sm-12 form-group">
                <label>Attachments</label>
                @Html.TextBoxFor(x => x.Upload, new { @class = "dropify", @type = "file", @multiple = "multiple" })
                @Html.ValidationMessageFor(model => model.Upload, "", new { @class = "text-danger" })
            </div>
            <div class="col-lg-12 form-group">
                <button type="submit" class="btn btn-indigo" name="Command" value="Add"><i class="fa fa-paper-plane" aria-hidden="true"></i> Submit</button>
            </div>

        </div>
        }

    </div>
</div>

Web/Views/HelpDesk/_StatusAdd.cshtml
@model Helpdesk.Status.Add

@using (Ajax.BeginForm("_StatusAdd", "HelpDesk",
        new { src = ViewBag.src },
         new AjaxOptions { HttpMethod = "POST", OnSuccess = "OnSuccess", OnBegin = "ShowLoadingDialog()" },
            new { @id = "_StatusAddForm" })
    )
{


    
    @Html.HiddenFor(x => Model.StatusID)
<div class="row">
    <div class="col-lg-12 col-md-12 col-sm-12 form-group">
        <label>Status Name <sup>*</sup></label>
        @Html.TextBoxFor(model => model.StatusName, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.StatusName, "", new { @class = "text-danger" })
    </div>
    <div class="col-lg-12 col-md-12 col-sm-12 form-group">
        <label>Display Name <sup>*</sup></label>
        @Html.TextBoxFor(model => model.DisplayName, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.DisplayName, "", new { @class = "text-danger" })
    </div>
    <div class="col-lg-12 col-md-12 col-sm-12 form-group">
        <label>Color</label>
        @Html.TextBoxFor(model => model.Color, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.Color, "", new { @class = "text-danger" })
    </div>
    <div class="col-lg-12 col-md-12 col-sm-12 form-group">
        <label>Icon </label>
        @Html.TextBoxFor(model => model.Icon, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.Icon, "", new { @class = "text-danger" })
    </div>
    


    <div class="col-lg-6 col-md-6 col-sm-6 form-group">
        <label>Priority</label>
        @Html.TextBoxFor(model => model.Priority, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.Priority, "", new { @class = "text-danger" })
    </div>

    <div class="col-lg-12 form-group">

        @if (Model.StatusID > 0)
        {
            <button type="submit" class="btn btn-indigo" name="Command" value="Add"><i class="fa fa-paper-plane" aria-hidden="true"></i> Update</button>
        }
        else
        {
            <button type="submit" class="btn btn-indigo" name="Command" value="Add"><i class="fa fa-paper-plane" aria-hidden="true"></i> Submit</button>
        }
    </div>

</div>
}