Web/Controllers/MastersController.cs
using DataAccess.CommanClass;
using DataAccess.Models;
using DataAccess.ModelsMaster;
using DataAccess.ModelsMasterHelper;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Web.CommonClass;

namespace Web.Controllers
{
    [CheckLoginFilter]
    public class MastersController : Controller
    {
        long LoginID = 0;
        string IPAddress = "";
        GetResponse getResponse;
        IMasterHelper Master;
        IToolHelper Tools;
        public MastersController()
        {
            getResponse = new GetResponse();
            long.TryParse(ClsApplicationSetting.GetSessionValue("LoginID"), out LoginID);
            IPAddress = ClsApplicationSetting.GetIPAddress();
            getResponse.IPAddress = IPAddress;
            getResponse.LoginID = LoginID;
            Master = new MasterModal();
            Tools = new ToolsModal();
        }

        public string RenderRazorViewToString(string viewName, object model)
        {
            ViewData.Model = model;
            using (var sw = new StringWriter())
            {
                var viewResult = ViewEngines.Engines.FindPartialView(ControllerContext,
                                                                         viewName);
                var viewContext = new ViewContext(ControllerContext, viewResult.View,
                                             ViewData, TempData, sw);
                viewResult.View.Render(viewContext, sw);
                viewResult.ViewEngine.ReleaseView(ControllerContext, viewResult.View);
                return sw.GetStringBuilder().ToString();
            }
        }

        [HttpPost]
        public ActionResult SaveMasterAll(string src, Masters.Add Modal, string Command)
        {
            PostResponse Result = new PostResponse();
            ViewBag.src = src;
            string[] GetQueryString = ClsApplicationSetting.DecryptQueryString(src);
            ViewBag.GetQueryString = GetQueryString;
            ViewBag.MenuID = GetQueryString[0];
            ViewBag.MasterID = GetQueryString[2];
            long MasterID = 0;
            long.TryParse(ViewBag.MasterID, out MasterID);
            Result.SuccessMessage = "Masters Can't Update";
            if (ModelState.IsValid)
            {
                Modal.LoginID = LoginID;
                Modal.IPAddress = IPAddress;
                Modal.MasterID = MasterID;
                Result = Master.fnSetMasters(Modal);
            }
            return Json(Result, JsonRequestBehavior.AllowGet);

        }

        public ActionResult DepartmentList(string src)
        {
            ViewBag.src = src;
            string[] GetQueryString = ClsApplicationSetting.DecryptQueryString(src);
            ViewBag.GetQueryString = GetQueryString;
            ViewBag.MenuID = GetQueryString[0];
            List<Department.List> result = new List<Department.List>();
            result = Master.GetDepartmentList(getResponse);
            return View(result);
        }
        public ActionResult _DepartmentAdd(string src)
        {
            ViewBag.src = src;
            string[] GetQueryString = ClsApplicationSetting.DecryptQueryString(src);
            ViewBag.GetQueryString = GetQueryString;
            ViewBag.MenuID = GetQueryString[0];
            ViewBag.DeptID = GetQueryString[2];
            long DeptID = 0;
            long.TryParse(ViewBag.DeptID, out DeptID);
            getResponse.ID = DeptID;
            Department.Add result = new Department.Add();
            if (DeptID > 0)
            {
                result = Master.GetDepartment(getResponse);
            }
            return PartialView(result);
        }

        [HttpPost]
        public ActionResult _DepartmentAdd(string src, Department.Add Modal, string Command)
        {
            PostResponse Result = new PostResponse();
            ViewBag.src = src;
            string[] GetQueryString = ClsApplicationSetting.DecryptQueryString(src);
            ViewBag.GetQueryString = GetQueryString;
            ViewBag.MenuID = GetQueryString[0];
            ViewBag.DeptID = GetQueryString[2];
            long DeptID = 0;
            long.TryParse(ViewBag.DeptID, out DeptID);
            Result.SuccessMessage = "Department Can't Update";
            if (ModelState.IsValid)
            {
                Modal.LoginID = LoginID;
                Modal.IPAddress = IPAddress;
                Modal.DeptID = DeptID;
                Result = Master.fnSetDepartment(Modal);

            }
            if (Result.Status)
            {
                Result.RedirectURL = "/Masters/DepartmentList?src=" + ClsCommon.Encrypt(ViewBag.MenuID.ToString() + "*/Masters/DepartmentList");
            }
            return Json(Result, JsonRequestBehavior.AllowGet);

        }



        public ActionResult DesignationList(string src)
        {
            ViewBag.src = src;
            string[] GetQueryString = ClsApplicationSetting.DecryptQueryString(src);
            ViewBag.GetQueryString = GetQueryString;
            ViewBag.MenuID = GetQueryString[0];

            List<Designation.List> result = new List<Designation.List>();
            result = Master.GetDesignationList(getResponse);
            return View(result);
        }
        public ActionResult _DesignationAdd(string src)
        {
            ViewBag.src = src;
            string[] GetQueryString = ClsApplicationSetting.DecryptQueryString(src);
            ViewBag.GetQueryString = GetQueryString;
            ViewBag.MenuID = GetQueryString[0];
            ViewBag.DesignID = GetQueryString[2];
            long DesignID = 0;
            long.TryParse(ViewBag.DesignID, out DesignID);
            getResponse.ID = DesignID;
            Designation.Add result = new Designation.Add();
            if (DesignID > 0)
            {
                result = Master.GetDesignation(getResponse);
            }
            return PartialView(result);
        }

        [HttpPost]
        public ActionResult _DesignationAdd(string src, Designation.Add Modal, string Command)
        {
            PostResponse Result = new PostResponse();
            ViewBag.src = src;
            string[] GetQueryString = ClsApplicationSetting.DecryptQueryString(src);
            ViewBag.GetQueryString = GetQueryString;
            ViewBag.MenuID = GetQueryString[0];
            ViewBag.DesignID = GetQueryString[2];
            long DesignID = 0;
            long.TryParse(ViewBag.DesignID, out DesignID);
            Result.SuccessMessage = "Designation Can't Update";
            if (ModelState.IsValid)
            {
                Modal.LoginID = LoginID;
                Modal.IPAddress = IPAddress;
                Modal.DesignID = DesignID;
                Result = Master.fnSetDesignation(Modal);
            }
            if (Result.Status)
            {
                Result.RedirectURL = "/Masters/DesignationList?src=" + ClsCommon.Encrypt(ViewBag.MenuID.ToString() + "*/Masters/DesignationList");
            }
            return Json(Result, JsonRequestBehavior.AllowGet);

        }


        public ActionResult ClientsList(string src)
        {
            ViewBag.src = src;
            string[] GetQueryString = ClsApplicationSetting.DecryptQueryString(src);
            ViewBag.GetQueryString = GetQueryString;
            ViewBag.MenuID = GetQueryString[0];
            List<Clients.List> result = new List<Clients.List>();
            result = Master.GetMaster_ClientsList(getResponse);
            return View(result);
        }
        public ActionResult _ClientsAdd(string src)
        {
            ViewBag.src = src;
            string[] GetQueryString = ClsApplicationSetting.DecryptQueryString(src);
            ViewBag.GetQueryString = GetQueryString;
            ViewBag.MenuID = GetQueryString[0];
            ViewBag.ClientID = GetQueryString[2];
            long ClientID = 0;
            long.TryParse(ViewBag.ClientID, out ClientID);
            getResponse.ID = ClientID;
            Clients.Add result = new Clients.Add();
            if (ClientID > 0)
            {
                result = Master.GetMaster_Clients(getResponse);
            }
            return PartialView(result);
        }

        [HttpPost]
        public ActionResult _ClientsAdd(string src, Clients.Add Modal, string Command)
        {
            PostResponse Result = new PostResponse();
            ViewBag.src = src;
            string[] GetQueryString = ClsApplicationSetting.DecryptQueryString(src);
            ViewBag.GetQueryString = GetQueryString;
            ViewBag.MenuID = GetQueryString[0];
            long ClientID = 0;
            long.TryParse(ViewBag.ClientID, out ClientID);
            
            Result.SuccessMessage = "Clients Can't Update";
            if (ModelState.IsValid)
            {
                Modal.LoginID = LoginID;
                Modal.IPAddress = IPAddress;
                Modal.ClientID = ClientID;
                Result = Master.fnSetClients(Modal);

            }
            if (Result.Status)
            {
                Result.RedirectURL = "/Masters/ClientsList?src=" + ClsCommon.Encrypt(ViewBag.MenuID.ToString() + "*/Masters/ClientsList");
            }
            return Json(Result, JsonRequestBehavior.AllowGet);

        }


        public ActionResult ClientsTranList(string src)
        {
            ViewBag.src = src;
            string[] GetQueryString = ClsApplicationSetting.DecryptQueryString(src);
            ViewBag.GetQueryString = GetQueryString;
            ViewBag.MenuID = GetQueryString[0];
            ViewBag.ClientID = GetQueryString[2];
            long ClientID = 0;
            long.TryParse(ViewBag.ClientID, out ClientID);
            getResponse.ID = 0;
            getResponse.AdditionalID = ClientID;
            List<ClientsTran.List> result = new List<ClientsTran.List>();
            result = Master.GetMaster_ClientsTranList(getResponse);

Web/Views/Masters/ClientsList.cshtml
@model IList<Clients.List>
@section style{
    @System.Web.Optimization.Styles.Render("~/bundle/dataTablecss")
}

@Html.Partial("ListHeader_Partial", "Clients List")

<div class="row">
    <div class="col-lg-12 ">
        <div class="card">
            <div class="card-body">
                <div class="">
                    <div class="table-responsive">
                        <table id="example" class="table table-bordered text-nowrap key-buttons">
                            <thead>
                                <tr>
                                    <th>S.no.</th>
                                    <th>Action</th>
                                    <th>Name</th>
                                    <th>Code</th>
                                    <th>Display Name</th>
                                    <th>Other Code</th>
                                    <th>Inserted Date</th>
                                    <th>Inserted by</th>
                                    <th>Updated Date</th>
                                    <th>Updated by</th>
                                    <th>IP Address</th>
                                </tr>

                            </thead>
                            <tbody>
                                @{ int count = 0;}
                                @foreach (var item in Model)
                                {
                                    count++;
                                <tr>
                                    <td>@count</td>
                                    <td>
                                        <input type="hidden" name="I" value="@item.ClientID" />
                                        <input type="hidden" name="N" value="@item.ClientCode" />


                                        @if (ClsApplicationSetting.GetSessionValue("Modify") == "True")
                                        {
                                            @Html.Raw(item.IsActive == true
                                      ? "<a  data-toggle='tooltip' data-original-title='Click to DeActivate' list='Clients_IsActive' OP='0' class='AIsActive' > <i class='fa fa-check-circle checkgreen' aria-hidden='true'></i></a>"
                                      : "<a data-toggle='tooltip' data-original-title='Click to Activate' list='Clients_IsActive' OP='1'  class='AIsActive' > <i class='fa fa-times-circle crossred' aria-hidden='true'></i></a>")



                                            <a title="Edit" onclick="ListHeaderAdd(@item.ClientID);" data-toggle='tooltip'> <i class="fa fa-pencil-square-o checkgreen" aria-hidden="true"></i> </a>
                                        }

                                    </td>
                                    <td>@item.ClientName</td>
                                    <td>
                                        @if (ClsApplicationSetting.GetSessionValue("Modify") == "True")
                                        {
                                            <strong>
                                                <a data-toggle='tooltip' data-title="click to view tran" class="green-clr" onclick="ShowLoadingDialog()" href="@Url.Action("ClientsTranList","Masters", new { src = ClsCommon.Encrypt(ViewBag.MenuID + "*/Masters/ClientsTranList*" + item.ClientID+"*"+item.ClientCode) })" data-toggle='tooltip'> @item.ClientCode </a>


                                            </strong>
                                        }
                                        else
                                        {
                                            @item.ClientCode
                                        }
                                    </td>
                                    <td>@item.DisplayName</td>
                                    <td>@item.OtherCode</td>
                                    <td>@item.CreatedDate</td>
                                    <td>@item.CreatedBy</td>
                                    <td>@item.ModifiedDate</td>
                                    <td>@item.ModifiedBy</td>
                                    <td>@item.IPAddress</td>
                                </tr>
                                }

                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>



<div class="modal fade pop-dgn" id="ViewModal">
    <div class="modal-dialog modal-md">
        <div class="modal-content">

            <div class="modal-header blk-gdn-btn">
                <h4 class="modal-title"><i class="fas fa-print"></i>Add Client </h4>
                <div class="close" data-dismiss="modal">&times;</div>
            </div>
            <!-- Modal body -->
            <div class="modal-body">
                <div id="TagetDiv"></div>
            </div>
        </div>
    </div>

</div>


@section scripts    {
    @System.Web.Optimization.Scripts.Render("~/bundle/dataTablesjs")

    @System.Web.Optimization.Scripts.Render("~/bundle/unobtrusivejs")

    <script>

         function ListHeaderAdd(ID) {
        if (ID == undefined)
        {
            ID = 0;
        }
			$.ajax({
                url: "/Masters/_ClientsAdd",
                type: "Get",
                data: { src: EncryptJSON(@ViewBag.MenuID+"*" + "/Masters/_ClientsAdd" + "*" + ID) },
                success: function (data)
                {
                    $("#TagetDiv").empty();
                    $("#TagetDiv").html(data);
                    $('#ViewModal').modal({
                        backdrop: 'static',
                        keyboard: false
                    })
                    
                     var form = $("form")
                .removeData("validator")
                .removeData("unobtrusiveValidation");
                    $.validator.unobtrusive.parse(form);
				},
				error: function (er) {
					alert(er);

				}
			});
            }


        function OnSuccess(obj) {
            if (obj.Status) {
                SuccessToaster(obj.SuccessMessage);
                window.location.reload();
            }
            else {
                CloseLoadingDialog();
                FailToaster(obj.SuccessMessage);

            }
        }

    </script>

}

Web/Views/Masters/_CityAdd.cshtml
@model City.Add

@using (Ajax.BeginForm("_CityAdd", "Masters",
        new { src = ViewBag.src},
         new AjaxOptions { HttpMethod = "POST", OnSuccess = "OnSuccess", OnBegin = "ShowLoadingDialog()" },
            new { @id = "_CityAddForm" })
    )
{

    @Html.HiddenFor(x => Model.CityID)
<div class="row">

    <div class="col-lg-6 col-md-6 col-sm-6 form-group">
        <label>State <sup>*</sup></label>
        @Html.DropDownListFor(x => Model.StateID, new SelectList(Model.StateList, "ID", "Name", Model.StateID), "Select", new { @class = "form-control  applyselect" })
        @Html.ValidationMessageFor(model => Model.StateID, "", new { @class = "text-danger" })
    </div>
    <div class="col-lg-6 col-md-6 col-sm-6 form-group">
        <label>City Name<sup>*</sup></label>
        @Html.TextBoxFor(model => model.CityName, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.CityName, "", new { @class = "text-danger" })
    </div>
    <div class="col-lg-6 col-md-6 col-sm-6 form-group">
        <label>City Code <sup>*</sup></label>
        @Html.TextBoxFor(model => model.CityCode, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.CityCode, "", new { @class = "text-danger" })
    </div>
    
    <div class="col-lg-6 col-md-6 col-sm-6 form-group">
        <label>Priority</label>
        @Html.TextBoxFor(model => model.Priority, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.Priority, "", new { @class = "text-danger" })
    </div>
    <div class="col-lg-12 form-group">

        @if (Model.CityID > 0)
        {
            <button type="submit" class="btn btn-indigo" name="Command" value="Add"><i class="fa fa-paper-plane" aria-hidden="true"></i> Update</button>
        }
        else
        {
            <button type="submit" class="btn btn-indigo" name="Command" value="Add"><i class="fa fa-paper-plane" aria-hidden="true"></i> Submit</button>
        }
    </div>

</div>
}

Web/Views/Masters/_ClientsTranAdd.cshtml
@model ClientsTran.Add



@using (Ajax.BeginForm("_ClientsTranAdd", "Masters",
        new { src = ViewBag.src },
         new AjaxOptions { HttpMethod = "POST", OnSuccess = "OnSuccess", OnBegin = "ShowLoadingDialog()" },
            new { @id = "_ClientsTranAddForm" })
    )
{


    @Html.HiddenFor(x => Model.ClientTranID)
    @Html.HiddenFor(x => Model.ClientID)
<div class="row">
    <div class="col-lg-3 col-md-3 col-sm-3 form-group">
        <label> Name<sup>*</sup></label>
        @Html.TextBoxFor(model => model.Name, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
    </div>
    <div class="col-lg-3 col-md-3 col-sm-3 form-group">
        <label>Code<sup>*</sup> </label>
        @Html.TextBoxFor(model => model.Code, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.Code, "", new { @class = "text-danger" })
    </div>
    <div class="col-lg-3 col-md-3 col-sm-3 form-group">
        <label>Print Name<sup>*</sup> </label>
        @Html.TextBoxFor(model => model.PrintName, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.PrintName, "", new { @class = "text-danger" })
    </div>

    <div class="col-lg-3 col-md-3 col-sm-3 form-group">
        <label>GST No<sup>*</sup> </label>
        @Html.TextBoxFor(model => model.GSTNo, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.GSTNo, "", new { @class = "text-danger" })
    </div>

    <div class="col-lg-3 col-md-3 col-sm-3 form-group">
        <label>PAN <sup>*</sup></label>
        @Html.TextBoxFor(model => model.PAN, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.PAN, "", new { @class = "text-danger" })
    </div>

    <div class="col-lg-3 col-md-3 col-sm-3 form-group">
        <label>Commission (%)<sup>*</sup></label>
        @Html.TextBoxFor(model => model.Commission, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.Commission, "", new { @class = "text-danger" })
    </div>

    <div class="col-lg-3 col-md-3 col-sm-3 form-group">
        <label>Country <sup>*</sup></label>
        @Html.DropDownListFor(x => Model.CountryID, new SelectList(Model.CountryList, "ID", "Name", Model.CountryID), "Select", new { @class = "form-control  applyselect" })
        @Html.ValidationMessageFor(model => Model.CountryID, "", new { @class = "text-danger" })
    </div>

    <div class="col-lg-3 col-md-3 col-sm-3 form-group">
        <label>State <sup>*</sup></label>
        @Html.DropDownListFor(x => Model.StateID, new SelectList(Model.StateList, "ID", "Name", Model.StateID), "Select", new { @class = "form-control  applyselect"})
        @Html.ValidationMessageFor(model => Model.StateID, "", new { @class = "text-danger" })
    </div>

    <div class="col-lg-12 col-md-12 col-sm-12 form-group">
        <label>Address <sup>*</sup></label>
        @Html.TextBoxFor(model => model.Address, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
    </div>

    <div class="col-lg-3 col-md-3 col-sm-3 form-group">
        <label>Zip Code <sup>*</sup></label>
        @Html.TextBoxFor(model => model.ZipCode, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.ZipCode, "", new { @class = "text-danger" })
    </div>
    <div class="col-lg-3 col-md-3 col-sm-3 form-group">
        <label>Phone</label>
        @Html.TextBoxFor(model => model.Phone, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
    </div>
    <div class="col-lg-3 col-md-3 col-sm-3 form-group">
        <label>Email</label>
        @Html.TextBoxFor(model => model.EmailID, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.EmailID, "", new { @class = "text-danger" })
    </div>

    <div class="col-lg-3 col-md-3 col-sm-3 form-group">
        <label>Priority</label>
        @Html.TextBoxFor(model => model.Priority, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.Priority, "", new { @class = "text-danger" })
    </div>

    <div class="col-lg-12 form-group">

        @if (Model.ClientTranID > 0)
        {
            <button type="submit" class="btn btn-indigo" name="Command" value="Add"><i class="fa fa-paper-plane" aria-hidden="true"></i> Update</button>
        }
        else
        {
            <button type="submit" class="btn btn-indigo" name="Command" value="Add"><i class="fa fa-paper-plane" aria-hidden="true"></i> Submit</button>
        }
    </div>

</div>
}

Web/Views/Masters/_CountryAdd.cshtml
@model Country.Add

@using (Ajax.BeginForm("_CountryAdd", "Masters",
        new { src = ViewBag.src},
         new AjaxOptions { HttpMethod = "POST", OnSuccess = "OnSuccess", OnBegin = "ShowLoadingDialog()" },
            new { @id = "_CountryAddForm" })
    )
{

    @Html.HiddenFor(x => Model.CountryID)
<div class="row">
    <div class="col-lg-6 col-md-6 col-sm-6 form-group">
        <label>Country Name<sup>*</sup></label>
        @Html.TextBoxFor(model => model.CountryName, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.CountryName, "", new { @class = "text-danger" })
    </div>

    <div class="col-lg-6 col-md-6 col-sm-6 form-group">
        <label>Country Code <sup>*</sup></label>
        @Html.TextBoxFor(model => model.CountryCode, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.CountryCode, "", new { @class = "text-danger" })
    </div>
    <div class="col-lg-6 col-md-6 col-sm-6 form-group">
        <label>Priority</label>
        @Html.TextBoxFor(model => model.Priority, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.Priority, "", new { @class = "text-danger" })
    </div>

    <div class="col-lg-12 form-group">

        @if (Model.CountryID > 0)
        {
            <button type="submit" class="btn btn-indigo" name="Command" value="Add"><i class="fa fa-paper-plane" aria-hidden="true"></i> Update</button>
        }
        else
        {
            <button type="submit" class="btn btn-indigo" name="Command" value="Add"><i class="fa fa-paper-plane" aria-hidden="true"></i> Submit</button>
        }
    </div>

</div>
}

Web/Views/Masters/_DealerTypeAdd.cshtml
@model DealerType.Add


@using (Ajax.BeginForm("_DealerTypeAdd", "Masters",
        new { src = ViewBag.src },
         new AjaxOptions { HttpMethod = "POST", OnSuccess = "OnSuccess", OnBegin = "ShowLoadingDialog()" },
            new { @id = "_DealerTypeAddForm" })
    )
{


    @Html.HiddenFor(x => Model.DealerTypeID)
    <div class="row">

        <div class="col-lg-6 col-md-6 col-sm-6 form-group">
            <label> Name<sup>*</sup></label>
            @Html.TextBoxFor(model => model.Name, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
        <div class="col-lg-6 col-md-6 col-sm-6 form-group">
            <label>Code <sup>*</sup></label>
            @Html.TextBoxFor(model => model.Code, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Code, "", new { @class = "text-danger" })
        </div>
        <div class="col-lg-6 col-md-6 col-sm-6 form-group">
            <label>Priority</label>
            @Html.TextBoxFor(model => model.Priority, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Priority, "", new { @class = "text-danger" })
        </div>

        <div class="col-lg-12 form-group">

            @if (Model.DealerTypeID > 0)
            {
                <button type="submit" class="btn btn-indigo" name="Command" value="Add"><i class="fa fa-paper-plane" aria-hidden="true"></i> Update</button>
            }
            else
            {
                <button type="submit" class="btn btn-indigo" name="Command" value="Add"><i class="fa fa-paper-plane" aria-hidden="true"></i> Submit</button>
            }
        </div>

    </div>
}

Web/Views/Masters/_DesignationAdd.cshtml
@model Designation.Add



@using (Ajax.BeginForm("_DesignationAdd", "Masters",
        new { src = ViewBag.src },
         new AjaxOptions { HttpMethod = "POST", OnSuccess = "OnSuccess", OnBegin = "ShowLoadingDialog()" },
            new { @id = "_DesignationAddForm" })
    )
{


    
    @Html.HiddenFor(x => Model.DesignID)
<div class="row">
    <div class="col-lg-6 col-md-6 col-sm-6 form-group">
        <label> Name<sup>*</sup></label>
        @Html.TextBoxFor(model => model.DesignName, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.DesignName, "", new { @class = "text-danger" })
    </div>
    <div class="col-lg-6 col-md-6 col-sm-6 form-group">
        <label>Code </label>
        @Html.TextBoxFor(model => model.DesignCode, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.DesignCode, "", new { @class = "text-danger" })
    </div>


    <div class="col-lg-6 col-md-6 col-sm-6 form-group">
        <label>Priority</label>
        @Html.TextBoxFor(model => model.Priority, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.Priority, "", new { @class = "text-danger" })
    </div>

    <div class="col-lg-12 form-group">

        @if (Model.DesignID > 0)
        {
            <button type="submit" class="btn btn-indigo" name="Command" value="Add"><i class="fa fa-paper-plane" aria-hidden="true"></i> Update</button>
        }
        else
        {
            <button type="submit" class="btn btn-indigo" name="Command" value="Add"><i class="fa fa-paper-plane" aria-hidden="true"></i> Submit</button>
        }
    </div>

</div>
}

Web/Views/Masters/_RegionAdd.cshtml
@model Region.Add

@using (Ajax.BeginForm("_RegionAdd", "Masters",
        new { src = ViewBag.src},
         new AjaxOptions { HttpMethod = "POST", OnSuccess = "OnSuccess", OnBegin = "ShowLoadingDialog()" },
            new { @id = "_RegionAddForm" })
    )
{

    @Html.HiddenFor(x => Model.RegionID)
<div class="row">

    <div class="col-lg-6 col-md-6 col-sm-6 form-group">
        <label>Country <sup>*</sup></label>
        @Html.DropDownListFor(x => Model.CountryID, new SelectList(Model.CountryList, "ID", "Name", Model.CountryID), "Select", new { @class = "form-control  applyselect" })
        @Html.ValidationMessageFor(model => Model.CountryID, "", new { @class = "text-danger" })
    </div>
    <div class="col-lg-6 col-md-6 col-sm-6 form-group">
        <label>Region Name<sup>*</sup></label>
        @Html.TextBoxFor(model => model.RegionName, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.RegionName, "", new { @class = "text-danger" })
    </div>
    <div class="col-lg-6 col-md-6 col-sm-6 form-group">
        <label>Region Code <sup>*</sup></label>
        @Html.TextBoxFor(model => model.RegionCode, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.RegionCode, "", new { @class = "text-danger" })
    </div>
    <div class="col-lg-6 col-md-6 col-sm-6 form-group">
        <label>Priority</label>
        @Html.TextBoxFor(model => model.Priority, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.Priority, "", new { @class = "text-danger" })
    </div>
    <div class="col-lg-12 form-group">

        @if (Model.RegionID > 0)
        {
            <button type="submit" class="btn btn-indigo" name="Command" value="Add"><i class="fa fa-paper-plane" aria-hidden="true"></i> Update</button>
        }
        else
        {
            <button type="submit" class="btn btn-indigo" name="Command" value="Add"><i class="fa fa-paper-plane" aria-hidden="true"></i> Submit</button>
        }
    </div>

</div>
}