Web/Controllers/OnboardingController.cs
using DataAccess.CommanClass;
using DataAccess.Models;
using DataAccess.ModelsMaster;
using DataAccess.ModelsMasterHelper;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Web.CommonClass;

namespace Web.Controllers
{
    [CheckLoginFilter]
    public class OnboardingController : Controller
    {
        long LoginID = 0;
        string IPAddress = "";
        GetResponse getResponse;
        IOnboardingHelper onboard;

        public OnboardingController()
        {

            getResponse = new GetResponse();
            long.TryParse(ClsApplicationSetting.GetSessionValue("LoginID"), out LoginID);
            IPAddress = ClsApplicationSetting.GetIPAddress();
            getResponse.IPAddress = IPAddress;
            getResponse.LoginID = LoginID;
            onboard = new OnboardingModal();

        }

        public ActionResult OnboardingList(string src)
        {
            ViewBag.src = src;
            string[] GetQueryString = ClsApplicationSetting.DecryptQueryString(src);
            ViewBag.GetQueryString = GetQueryString;
            ViewBag.MenuID = GetQueryString[0];
            MyTab.Approval Modal = new MyTab.Approval();
            Modal.Approved = -1;
            Modal.LoginID = LoginID;
            return View(Modal);
        }
        public ActionResult _OnboardingList(string src, MyTab.Approval Modal)
        {
            ViewBag.src = src;
            string[] GetQueryString = ClsApplicationSetting.DecryptQueryString(src);
            ViewBag.GetQueryString = GetQueryString;
            ViewBag.MenuID = GetQueryString[0];
            Modal.LoginID = LoginID;
            Modal.IPAddress = IPAddress;
            List<Onboarding.List> result = new List<Onboarding.List>();
            result = onboard.GetOnboarding_List(Modal);
            return PartialView(result);

        }

        public ActionResult _CreateOnboarding(string src)
        {
            ViewBag.src = src;
            string[] GetQueryString = ClsApplicationSetting.DecryptQueryString(src);
            ViewBag.GetQueryString = GetQueryString;
            ViewBag.MenuID = GetQueryString[0];
            Onboarding.Create result = new Onboarding.Create();
            return PartialView(result);

        }

        [HttpPost]
        public ActionResult _CreateOnboarding(string src, Onboarding.Create Modal, string Command)
        {
            PostResponse Result = new PostResponse();
            ViewBag.src = src;
            string[] GetQueryString = ClsApplicationSetting.DecryptQueryString(src);
            ViewBag.GetQueryString = GetQueryString;
            ViewBag.MenuID = GetQueryString[0];
            Result.SuccessMessage = "Can't Create";
            if (ModelState.IsValid)
            {
                Modal.LoginID = LoginID;
                Modal.IPAddress = IPAddress;
                Modal.Token= Guid.NewGuid().ToString();
                Result = onboard.fnSetOnboarding_Create(Modal);
                
            }
            return Json(Result, JsonRequestBehavior.AllowGet);

        }

        public ActionResult _ViewOnboarding(string src)
        {
            ViewBag.src = src;
            string[] GetQueryString = ClsApplicationSetting.DecryptQueryString(src);
            ViewBag.GetQueryString = GetQueryString;
            ViewBag.MenuID = GetQueryString[0];
            ViewBag.AppID = GetQueryString[2];
            long AppID = 0;
            long.TryParse(ViewBag.AppID, out AppID);
            Onboarding.View result = new Onboarding.View();
            getResponse.ID = AppID;
            result = onboard.GetOnboarding_View(getResponse);
            return PartialView(result);

        }
        [HttpPost]
        public ActionResult OnboardingApprove(string src, FormCollection form, string Command)
        {
            PostResponse Result = new PostResponse();
            ViewBag.src = src;
            string[] GetQueryString = ClsApplicationSetting.DecryptQueryString(src);
            ViewBag.GetQueryString = GetQueryString;
            ViewBag.MenuID = GetQueryString[0];
            int Approved = 0;
            int.TryParse(Command, out Approved);
            string AppID = form["AppID"].ToString();
            if (!string.IsNullOrEmpty(AppID))
            {
                Onboarding.ApprovalAction Modal = new Onboarding.ApprovalAction();
                Modal.Approved = Approved;
                Modal.ApprovedRemarks = form["ApproveRemarks"].ToString();
                if (string.IsNullOrEmpty(Modal.ApprovedRemarks))
                {
                    Result.SuccessMessage = "Remarks can't be blank";
                    return Json(Result, JsonRequestBehavior.AllowGet);
                }
                Modal.LoginID = LoginID;
                Modal.IPAddress = IPAddress;
                Modal.IDs = AppID.ToString();
                Result = onboard.fnSetOnboardingApproval(Modal);
            }
            return Json(Result, JsonRequestBehavior.AllowGet);
        }

    }
}

Web/Views/Onboarding/OnboardingList.cshtml
@model MyTab.Approval
@section style{
    @System.Web.Optimization.Styles.Render("~/bundle/dataTablecss")
}

@Html.Partial("ListHeader_Partial", "Onboarding List")

<div class="row">
    <div class="col-lg-12 ">
        <div class="card">
            <div class="card-body">
                <div class="">

                    
                    @using (Ajax.BeginForm("_OnboardingList", "Onboarding",
                             new { src = ClsCommon.Encrypt(ViewBag.MenuID + "*/Onboarding/_OnboardingList") },
                              new AjaxOptions { HttpMethod = "POST", OnSuccess = "OnSuccess", OnBegin = "ShowLoadingDialog()" },
                                 new { @id = "_OnboardingList" })
                         )
                    {
                        <div class="row">
                            <div class="tabmargin">
                                @Html.HiddenFor(x => x.Approved)
                                <ul id="tabs" class="nav nav-tabs " role="tablist">
                                    <li class="nav-item"> <a tabvalue="-1" class="nav-link ripplelink AnchorApproval @(Model.Approved == -1 ? "active" : "")" data-toggle="tab" role="tab">Created</a> </li>
                                    <li class="nav-item"> <a tabvalue="0" class="nav-link ripplelink AnchorApproval @(Model.Approved == 0 ? "active" : "")" data-toggle="tab" role="tab">Pending</a> </li>
                                    <li class="nav-item"> <a tabvalue="1" class="nav-link ripplelink AnchorApproval @(Model.Approved == 1 ? "active" : "") " data-toggle="tab" role="tab">Approved</a></li>
                                    <li class="nav-item"> <a tabvalue="2" class="nav-link ripplelink AnchorApproval @(Model.Approved == 2 ? "active" : "") " data-toggle="tab" role="tab">Resubmit</a></li>
                                </ul>

                            </div>
                            <div class="col-sm-2 form-group" style="display:none">
                                <label class="small">&nbsp;</label>
                                <button type="submit" id="btnSearch" name="Command" value="Add" class="btn btndefault pull-right form-control">
                                    <i class="fa fa-search"></i>  Search
                                </button>
                            </div>
                        </div>
                    }

                    <div class="row">
                        <div class="col-md-12">
                            <div id="TargetDiv"> </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>

</div>




<div class="modal fade pop-dgn" id="ViewModal">
    <div class="modal-dialog modal-md">
        <div class="modal-content">

            <div class="modal-header blk-gdn-btn">
                <h4 class="modal-title"><i class="fas fa-print"></i>Create Onboarding </h4>
                <div class="close" data-dismiss="modal">&times;</div>
            </div>
            <!-- Modal body -->
            <div class="modal-body">
                <div id="TagetDiv"></div>
            </div>
        </div>
    </div>

</div>


<div class="modal fade pop-dgn" id="ViewFullModal">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">

            <div class="modal-header blk-gdn-btn">
                <h4 class="modal-title"><i class="fas fa-print"></i>View Onboarding </h4>
                <div class="close" data-dismiss="modal">&times;</div>
            </div>
            <!-- Modal body -->
            <div class="modal-body">
                <div id="ViewTagetDiv"></div>
            </div>
        </div>
    </div>

</div>

@section scripts    {
    @System.Web.Optimization.Scripts.Render("~/bundle/dataTablesjs")

    @System.Web.Optimization.Scripts.Render("~/bundle/unobtrusivejs")

<script>

         function ListHeaderAdd(ID) {
			$.ajax({
                url: "/Onboarding/_CreateOnboarding",
                type: "Get",
                data: { src: EncryptJSON(@ViewBag.MenuID+"*" + "/Onboarding/_CreateOnboarding" + "*" + ID) },
                success: function (data)
                {
                    $("#TagetDiv").empty();
                    $("#TagetDiv").html(data);
                    $('#ViewModal').modal({
                        backdrop: 'static',
                        keyboard: false
                    })
                     var form = $("form")
                .removeData("validator")
                .removeData("unobtrusiveValidation");
                    $.validator.unobtrusive.parse(form);
				},
				error: function (er) {
					alert(er);

				}
			});
            }


        function OnBegin() {
            $("#TargetDiv").empty();
            $("#TargetDiv").html('<img src="/assets/design/images/loader.gif" class="imgloader" />');
        }
        $(document).ready(function () {
            $("#btnSearch").click();
        });


        $('.AnchorApproval').on('click', function (e) {
            e.preventDefault();
            e.stopPropagation();
            var att = $(this).attr("tabvalue");
            $(".AnchorApproval.active").removeClass("active");
            $(this).addClass("active");
            $("#Approved").val(att);
            $('#btnSearch').click();
        });


    function OnOnboardingSuccess(obj) {
        if (obj.Status) {
            $('#ViewModal').modal('hide');
            SuccessToaster(obj.SuccessMessage);
            $('#btnSearch').click();
        }
        else {
            CloseLoadingDialog();
            FailToaster(obj.SuccessMessage);

        }
    }

        function OnSuccess(obj) {
            $("#TargetDiv").empty();
            $("#TargetDiv").html(obj);
            CloseLoadingDialog();
            DatatableScripts();
        }


    function ViewOnboarding(obj) {
        var ID = $(obj).closest("tr").find("input:hidden[name=I]").val();
			$.ajax({
                url: "/Onboarding/_ViewOnboarding",
                type: "Get",
                data: { src: EncryptJSON(@ViewBag.MenuID+"*/Onboarding/_ViewOnboarding*" + ID) },
                success: function (data)
                {
                    $("#ViewTagetDiv").empty();
                    $("#ViewTagetDiv").html(data);
                    $('#ViewFullModal').modal({
                        backdrop: 'static',
                        keyboard: false
                    })
                     var form = $("form")
                .removeData("validator")
                .removeData("unobtrusiveValidation");
                    $.validator.unobtrusive.parse(form);
				},
				error: function (er) {
					alert(er);

				}
			});
    }

    function OnboardingApproveSuccess(obj) {
        if (obj.Status) {
            $('#ViewFullModal').modal('hide');
            SuccessToaster(obj.SuccessMessage);
            $('#btnSearch').click();
        }
        else {
            CloseLoadingDialog();
            FailToaster(obj.SuccessMessage);

        }
    }


</script>

}

Web/Views/Onboarding/_CreateOnboarding.cshtml
@model Onboarding.Create

@using (Ajax.BeginForm("_CreateOnboarding", "Onboarding",
        new { src = ViewBag.src },
         new AjaxOptions { HttpMethod = "POST", OnSuccess = "OnOnboardingSuccess", OnBegin = "ShowLoadingDialog()" },
            new { @id = "_CreateOnboardingForm" })
    )
{
<div class="row">
    <div class="col-lg-6 col-md-6 col-sm-6 form-group">
        <label>Name<sup>*</sup></label>
        @Html.TextBoxFor(model => model.Name, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
    </div>
    <div class="col-lg-6 col-md-6 col-sm-6 form-group">
        <label>Date of Birth <sup>*</sup></label>
        @Html.TextBoxFor(model => model.DOB, new { @class = "form-control", @type = "date" })
        @Html.ValidationMessageFor(model => model.DOB, "", new { @class = "text-danger" })
    </div>

    <div class="col-lg-6 col-md-6 col-sm-6 form-group">
        <label>Gender</label>
        @Html.EnumDropDownListFor(m => m.Gender, "Select", new { @class = "form-control applyselect" })
        @Html.ValidationMessageFor(m => m.Gender)
    </div>
    <div class="col-lg-6 col-md-6 col-sm-6 form-group">
        <label>Email<sup>*</sup></label>
        @Html.TextBoxFor(model => model.EmailID, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.EmailID, "", new { @class = "text-danger" })
    </div>
    <div class="col-lg-6 col-md-6 col-sm-6 form-group">
        <label>Mobile<sup>*</sup></label>
        @Html.TextBoxFor(model => model.Mobile, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.Mobile, "", new { @class = "text-danger" })
    </div>
    <div class="col-lg-6 col-md-6 col-sm-6 form-group">
        <label>Father's Name<sup>*</sup></label>
        @Html.TextBoxFor(model => model.FatherName, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.FatherName, "", new { @class = "text-danger" })
    </div>
    <div class="col-lg-12 form-group">
        <button type="submit" class="btn btn-indigo" name="Command" value="Add"><i class="fa fa-paper-plane" aria-hidden="true"></i> Create</button>
    </div>

</div>
}

Web/Views/Onboarding/_OnboardingList.cshtml
@model IList<Onboarding.List>

<div class="table-responsive">
    <table id="example" class="table table-bordered text-nowrap key-buttons">
        <thead>
            <tr>
                <th>S.no.</th>
                <th>Doc No</th>
                <th>Name</th>
                <th>Gender</th>
                <th>Mobile</th>
                <th>EmailID</th>
                <th>DOB </th>
                <th>Created Date</th>
                <th>IP Address</th>
            </tr>

        </thead>
        <tbody>
            @{ int count = 0;}
            @foreach (var item in Model)
            {
                count++;
            <tr>
                <td>
                    @count
                    <input type="hidden" name="I" value="@item.AppID" />
                    <input type="hidden" name="N" value="@item.DocNo" />
                </td>

                <td>
                    <a title="click to view details" class="green-clr" onclick="ViewOnboarding(this)" data-toggle='tooltip'> @item.DocNo</a>
                </td>

                @if (item.Approved <=0 || item.Approved==2)
                {
                    <td>
                        <a title="click to fill form" href="/OnboardBasicDetails/@item.Token" target="_blank" class="green-clr"> @item.Name</a>
                    </td>
                }
                else
                {
                    <td>
                        @item.Name
                    </td>
                   
                }


                <td>@item.Gender</td>
                <td>@item.Mobile</td>
                <td>@item.EmailID</td>
                <td>@item.DOB</td>
                <td>@item.CreatedDate</td>
                <td>@item.IPAddress</td>
            </tr>
            }

        </tbody>
    </table>
</div>

Web/Views/Onboarding/_ViewOnboarding.cshtml
@model Onboarding.View

<div class="tabs effect-4">
    <!-- tab-title -->
    <input type="radio" id="tab-1" name="tab-effect-4" checked="checked">
    <span>
        <i class="fa fa-home"></i><span>Basic Details</span>
    </span>
    <input type="radio" id="tab-2" name="tab-effect-4">
    <span>
        <i class="fa fa-bookmark"></i><span>Bank Details</span>
    </span>

    <input type="radio" id="tab-3" name="tab-effect-4">
    <span>
        <i class="fa fa-cloud-upload"></i><span>Upload Documents</span>
    </span>

    <div class="tab-content">
        <section id="tab-item-1">
            <div class="row">
                <div class="col-lg-4 col-md-4 col-sm-4 form-group">
                    <label> Doc No</label>
                    <p> @Model.DocNo</p>
                </div>
                <div class="col-lg-4 col-md-4 col-sm-4 form-group">
                    <label> Doc Date</label>
                    <p> @Model.DocDate</p>
                </div>
                <div class="col-lg-4 col-md-4 col-sm-4 form-group">
                    <label> Name</label>
                    <p> @Model.Name</p>
                </div>
                <div class="col-lg-4 col-md-4 col-sm-4 form-group">
                    <label> Gender</label>
                    <p> @Model.Gender</p>
                </div>
                <div class="col-lg-4 col-md-4 col-sm-4 form-group">
                    <label> Father Name</label>
                    <p> @Model.FatherName</p>
                </div>
                <div class="col-lg-4 col-md-4 col-sm-4 form-group">
                    <label> DOB</label>
                    <p> @Model.DOB</p>
                </div>
                <div class="col-lg-4 col-md-4 col-sm-4 form-group">
                    <label> Mobile</label>
                    <p> @Model.Mobile</p>
                </div>
                <div class="col-lg-4 col-md-4 col-sm-4 form-group">
                    <label> Email</label>
                    <p> @Model.EmailID</p>
                </div>


                <div class="col-lg-4 col-md-4 col-sm-4 form-group">
                    <label>Blood Group </label>
                    <p> @Model.BloodGroup</p>
                </div>

                <div class="col-lg-4 col-md-4 col-sm-4 form-group">
                    <label> Marital Status</label>
                    <p> @Model.MaritalStatus</p>
                </div>


                <div class="col-lg-4 col-md-4 col-sm-4 form-group">
                    <label> Country</label>
                    <p> @Model.CountryName</p>
                </div>
                <div class="col-lg-4 col-md-4 col-sm-4 form-group">
                    <label> Region</label>
                    <p> @Model.RegionName</p>
                </div>
                <div class="col-lg-4 col-md-4 col-sm-4 form-group">
                    <label> State</label>
                    <p> @Model.StateName</p>
                </div>
                <div class="col-lg-4 col-md-4 col-sm-4 form-group">
                    <label> City</label>
                    <p> @Model.CityName</p>
                </div>
                <div class="col-lg-4 col-md-4 col-sm-4 form-group">
                    <label> Address</label>
                    <p> @Model.Address</p>
                </div>
                <div class="col-lg-4 col-md-4 col-sm-4 form-group">
                    <label> PIN Code</label>
                    <p> @Model.PINCode</p>
                </div>

                <div class="col-lg-4 col-md-4 col-sm-4 form-group">
                    <label>Vaccination</label>
                    <p> @Model.VaccinationDetails</p>
                </div>
                <div class="col-lg-4 col-md-4 col-sm-4 form-group">
                    <label>Aadhar No</label>
                    <p> @Model.AadharNo</p>
                </div>
                <div class="col-lg-4 col-md-4 col-sm-4 form-group">
                    <label>PAN</label>
                    <p> @Model.PAN</p>
                </div>
                <div class="col-lg-4 col-md-4 col-sm-4 form-group">
                    <label>ESIC</label>
                    <p> @Model.ESIC</p>
                </div>
                <div class="col-lg-4 col-md-4 col-sm-4 form-group">
                    <label>UAN</label>
                    <p> @Model.UAN</p>
                </div>


            </div>
        </section>
        
        <section id="tab-item-2">
            <div class="row">
                <div class="col-lg-4 col-md-4 col-sm-4 form-group">
                    <label> Bank Name</label>
                    <p> @Model.BankName</p>
                </div>
                <div class="col-lg-4 col-md-4 col-sm-4 form-group">
                    <label> Account No</label>
                    <p> @Model.AccountNo</p>
                </div>
                <div class="col-lg-4 col-md-4 col-sm-4 form-group">
                    <label>Branch</label>
                    <p> @Model.BankBranch</p>
                </div>
                <div class="col-lg-4 col-md-4 col-sm-4 form-group">
                    <label> IFSC Code</label>
                    <p> @Model.IFSCCode</p>
                </div>
                <div class="col-lg-4 col-md-4 col-sm-4 form-group">
                    <label> Nominee Name</label>
                    <p> @Model.NomineeName</p>
                </div>
                <div class="col-lg-4 col-md-4 col-sm-4 form-group">
                    <label> Nominee DOB</label>
                    <p> @Model.NomineeDOB</p>
                </div>
                <div class="col-lg-4 col-md-4 col-sm-4 form-group">
                    <label> Nominee Relation</label>
                    <p> @Model.NomineeRelation</p>
                </div>
            </div>
        </section>
        <section id="tab-item-3">
            <div class="row">
                @if (Model.DocumentsList != null)
                {
                    <table id="tbldoc" class="table" cellpadding="0" cellspacing="0">
                        <thead>
                            <tr>
                                <th>S.No</th>
                                <th>File</th>
                                <th>Description</th>
                            </tr>
                        </thead>

                        <tbody>
                            @{ int count = 0;}
                            @foreach (var item in Model.DocumentsList)
                            {
                                count++;
                                <tr>
                                    <td>@count</td>
                                    <td><a target="_blank" href="@item.AttachmentPath">Documents</a> </td>
                                    <td>@item.Description</td>
                                </tr>
                            }
                        </tbody>
                    </table>
                }
            </div>
        </section>

    </div>

    @if (Model.Approved > 0)
    {
        <div class="field1 my-2 row">
            <div class="col-xl-3 col-md-6 col-sm-12">
                <div class="form-floating form-group">
                    <p class="@Model.ApprovedStatus">@Model.ApprovedStatus</p>

                </div>
            </div>
            <div class="col-xl-3 col-md-6 col-sm-12">
                <div class="form-floating form-group">
                    <p style="color:blue">@Model.ApprovedRemarks</p>

                </div>
            </div>
        </div>
    }
</div>

@if (Model.Approved == 0)
{
    <footer>
        @using (Ajax.BeginForm("OnboardingApprove", "Onboarding",
                      new { src = ClsCommon.Encrypt(ViewBag.MenuID + "*/Onboarding/OnboardingApprove") },
                       new AjaxOptions { HttpMethod = "POST", OnSuccess = "OnboardingApproveSuccess", OnBegin = "ShowLoadingDialog()" },
                          new { @id = "OnboardingApproveForm" })
                  )
        {
            <div class="col-sm-12 form-group ">
                <label>Reason</label>
                <input type="hidden" id="AppID" name="AppID" value="@Model.AppID" />
                <textarea name="ApproveRemarks" class="form-control" Placeholder="Reason"></textarea>
            </div>
            <div class="col-sm-12 text-center mt-3">
                <button type="button" class="btn cnl-btn ripplelink " data-dismiss="modal"><i class="fa fa-times"></i>Close</button>
                <button type="submit" class="btn apr-btn " name="Command" value="1">
                    <i class="fa fa-check" aria-hidden="true"></i>
                    Approve
                </button>
                <button type="submit" class="btn btn-danger " name="Command" value="2">
                    <i class="fa fa-check" aria-hidden="true"></i>
                    Resubmit
                </button>
            </div>
        }
    </footer>
}